Quiz-Application-MVC/Models/ErrorViewModel.cs
namespace Quiz_Application_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Quiz-Application-MVC/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using Quiz.Facade;
using Quiz.Facade.Facades;
using Quiz.Models.FormattedData;
using Quiz.Models.ViewModels;
using Quiz.Services.ModelPreparatorService;
using Quiz_Application_MVC.Models;
using System.Diagnostics;

namespace Quiz_Application_MVC.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;
        private readonly IRepositoryFacade<QuizFormattedData, Quiz.Models.DataModels.Quiz> _facade;
        private readonly IQuizViewModelPreparator _modelPreparator;
        public MainController(ILogger<MainController> logger, FacadeFactory factory, IQuizViewModelPreparator modelPreparator)
        {
            _logger = logger;
            _facade = factory.GetFacade<QuizFormattedData, Quiz.Models.DataModels.Quiz>();
            _modelPreparator = modelPreparator;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _facade.GetAll();

            if (!result.Success)
            {
                return NotFound(result.ErrorMessage);
            }

            var newQuiz = _modelPreparator.GetNewViewModel();
            ViewBag.NewQuiz = newQuiz;

            return View(result.Data);

        }

        
        [HttpPost]
        public async Task<IActionResult> AddQuizModal(ManageQuizViewModel quizViewModel)
        {
            quizViewModel.Quiz.questions.Add(quizViewModel.Question);
            quizViewModel.Question = null;
            return RedirectToAction("Index");
        }

        public IActionResult ShowAddQuizModal()
        {
            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Quiz-Application-MVC/Controllers/ManageQuizController.cs
using Microsoft.AspNetCore.Mvc;
using Quiz.Facade;
using Quiz.Facade.Facades;
using Quiz.Models.FormattedData;
using Quiz.Models.ResponseModels;
using Quiz.Models.ViewModels;
using Quiz.Services;
using Quiz.Services.ModelPreparatorService;

namespace Quiz_Application_MVC.Controllers
{
    public class ManageQuizController : Controller
    {
        private readonly ILogger<ManageQuizController> _logger;
        private readonly IRepositoryFacade<QuizFormattedData, Quiz.Models.DataModels.Quiz> _facade;
        private readonly IQuizViewModelPreparator _modelPreparator;
        private readonly TempDataStorage _storage;
        public ManageQuizController(ILogger<ManageQuizController> logger, FacadeFactory factory, IQuizViewModelPreparator modelPreparator, TempDataStorage storage)
        {
            _logger = logger;
            _facade = factory.GetFacade<QuizFormattedData, Quiz.Models.DataModels.Quiz>();
            _modelPreparator = modelPreparator;
            _storage = storage;
        }
        public IActionResult AddQuizView([FromQuery] string mode)
        {
            _storage.ManageMode = mode;

            var quizViewModel = _modelPreparator.GetNewViewModel();

            return View(quizViewModel);
        }

        public async Task<IActionResult> EditQuiz([FromRoute] int id, [FromQuery] string mode)
        {
            _storage.ManageMode = mode;

            var response = await _facade.GetById(id);

            if (!response.Success)
            {
                return NotFound();
            }

            var quizViewModel = new ManageQuizViewModel();
            quizViewModel.Quiz = response.Data.First();

            return View("AddQuizView", quizViewModel);
        }

        public async Task<IActionResult> DeleteQuiz([FromRoute] int id)
        {
            var response = await _facade.Delete(id);

            if (!response.Success)
            {
                return BadRequest();
            }

            return RedirectToAction("Index", "Main");
        }

        [HttpPost]
        public IActionResult DeleteQuestion(ManageQuizViewModel model,[FromRoute] int id)
        {
            ModelState.Clear();

            _modelPreparator.DeleteQuestionFromViewModel(model, id);

            return View("AddQuizView", model);
        }

        [HttpPost]
        public IActionResult DeleteAnswer(ManageQuizViewModel model, [FromRoute] int id, [FromRoute] int questId)
        {
            ModelState.Clear();

            _modelPreparator.DeleteAnswerFromViewModel(model, questId, id);

            return View("AddQuizView", model);
        }

        [HttpPost]
        public IActionResult AddQuestion(ManageQuizViewModel model, [FromRoute] int id)
        {
            ModelState.Clear();

            _modelPreparator.AddQuestionToViewModel(model, id);

            return View("AddQuizView", model);
        }

        [HttpPost]
        public IActionResult AddAnswer(ManageQuizViewModel model, [FromRoute] int id)
        {
            ModelState.Clear();

            _modelPreparator.AddAnswerToViewModel(model, id);

            return View("AddQuizView", model);
        }

        [HttpPost]
        public async Task<IActionResult> SaveQuizChanges(ManageQuizViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("AddQuizView", model);
            }

            Response<QuizFormattedData> response = new();

            if(_storage.ManageMode == "Create")
            {
                response = await _facade.Add(model.Quiz);
            }
            else if(_storage.ManageMode == "Update")
            {
                response = await _facade.Update(model.Quiz);
            }

            if (!response.Success)
            {
                TempData["ErrorMessage"] = response.ErrorMessage;
                return View("AddQuizView", model);
            }

            return RedirectToAction("Index", "Main");
        }
    }
}

Quiz-Application-MVC/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using Quiz.Facade;
using Quiz.Facade.Facades;
using Quiz.Models.DataModels;
using Quiz.Models.FormattedData;
using Quiz.Models.ViewModels;
using Quiz.Services.ResultCalculatorService;

namespace Quiz_Application_MVC.Controllers
{
    public class QuizController : Controller
    {
        private readonly IRepositoryFacade<QuizFormattedData, Quiz.Models.DataModels.Quiz> _facade;
        private readonly IResultCalculatorService _calculatorService;

        public QuizController(FacadeFactory factory,
            IResultCalculatorService calculatorService)
        {
            _facade = factory.GetFacade<QuizFormattedData, Quiz.Models.DataModels.Quiz>();
            _calculatorService = calculatorService;
        }

        public async Task<IActionResult> StartQuiz([FromRoute] int id)
        {
            var quiz = await _facade.GetById(id);

            var viewModel = new QuizViewModel(quiz.Data.First());
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> FinishQuiz(QuizViewModel viewModel, [FromRoute] int id)
        {
            var response = await _calculatorService.CalculateResult(viewModel, id);

            if (!response.Success)
            {
                return NotFound(response.ErrorMessage);
            }

            var data = response.Data.FirstOrDefault();

            return View("QuizResults", data);
        }
    }
}

Quiz-Application-MVC/Views/Main/Index.cshtml
@model IList<QuizFormattedData>
@{
    ViewData["Title"] = "Quiz Page";
    var list = new List<string> { "Header" };
}

<div class="container">
    <div class="row m-auto border-bottom border-dark-subtle pb-2" style="height:50px; width:100%">
        <div class="col d-flex align-items-center">
            <h2 class="m-0">
                Custom Quizes
            </h2>
        </div>
        <div class="col text-end d-flex align-items-center justify-content-end">
            <a asp-route-mode="Create" asp-controller="ManageQuiz" asp-action="AddQuizView" class="btn btn-info">
                Add new
            </a>
        </div>
    </div>
    <div class="row pt-3">
        @for (var i = 0; i < Model.Count; i++)
        {
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header row d-flex">
                        <div class="col align-self-center">
                            <h4 class="my-0 font-weight-normal">@Model[i].Name</h4>
                        </div>
                        <div class="col-auto align-self-end">
                            <a class="btn btn-outline-primary" asp-route-mode="Update" asp-controller="ManageQuiz" asp-action="EditQuiz" asp-route-id="@Model[i].Id">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a class="btn btn-outline-primary" asp-controller="ManageQuiz" asp-action="DeleteQuiz" asp-route-id="@Model[i].Id">
                                <i class="bi bi-trash3"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row h4 ">
                            <p class="font-monospace">
                                Number of questions: @Model[i].QuestionsCount
                            </p>
                        </div>
                        <div class="row">
                            <div class="col h4 align-self-center mb-0" style="font-weight:bold;">
                                @Model[i].CreationDate
                            </div>
                            <div class="col-auto">
                                <a asp-route-id="@Model[i].Id" asp-action="StartQuiz" asp-controller="Quiz" type="button" class="btn btn-lg btn-block btn-outline-primary">Start</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>


@section Scripts{
    @{
          //<partial name="_AddQuizModal" model="new QuizViewModel()"></partial>
    }
}

Quiz-Application-MVC/Views/ManageQuiz/AddQuizView.cshtml
@model ManageQuizViewModel

@{
    string text = TempData["ErrorMessage"] as string ?? "";
}

<form class="form" method="post" action="AddQuizModal">
    <div class="d-none">
        <label asp-for="@Model.Quiz.id" class="col-form-label"></label>
        <input asp-for="@Model.Quiz.id" type="text" class="form-control bg-body-secondary" />
    </div>
    <div class="d-none">
        <label asp-for="@Model.Quiz.creationDate" class="col-form-label"></label>
        <input asp-for="@Model.Quiz.creationDate" type="text" class="form-control bg-body-secondary" />
    </div>
    <div class="form-group mb-3 w-50">
        <label asp-for="@Model.Quiz.name" class="col-form-label"></label>
        <input asp-for="@Model.Quiz.name" id="name" type="text" class="form-control bg-body-secondary" />
        <span asp-validation-for="@Model.Quiz.name" class="text-danger"></span>
    </div>
    <div class="questions mb-3">
        @for (int i = 0; i < Model.Quiz.questions?.Count; i++)
        {
            <div class="row">
                <div class="col" style="padding-right:0px;">
                    <button class="btn btn-primary w-100" type="button" data-toggle="collapse" data-target="#question@(i)">@("Question " + (i + 1))</button>
                </div>
                <div class="col-auto">
                    <button asp-route-id="@(i)" asp-action="DeleteQuestion" asp-controller="ManageQuiz" class="btn btn-danger w-100" type="submit"><i class="bi bi-trash"></i></button>
                </div>
            </div>
            <div class="mb-3">
                <div class="collapse show" id="question@(i)">
                    <div class="form-group d-flex ">

                        <div class="d-none">
                            <label asp-for="@Model.Quiz.questions[i].id" class="col-form-label"></label>
                            <input asp-for="@Model.Quiz.questions[i].id" type="text" class="form-control bg-body-secondary" />
                        </div>
                        <div class="d-none">
                            <label asp-for="@Model.Quiz.questions[i].quizId" class="col-form-label"></label>
                            <input asp-for="@Model.Quiz.questions[i].quizId" type="text" class="form-control bg-body-secondary" />
                        </div>

                        <div class="w-50 m-1">
                            <label asp-for="@Model.Quiz.questions[i].value" class="col-form-label"></label>
                            <input asp-for="@Model.Quiz.questions[i].value" type="text" class="form-control bg-body-secondary" />
                            <span asp-validation-for="@Model.Quiz.questions[i].value" class="text-danger"></span>
                        </div>


                        <div class="w-50 m-1">
                            <label asp-for="@Model.Quiz.questions[i].correctAnswer" class="col-form-label"></label>
                            <input asp-for="@Model.Quiz.questions[i].correctAnswer" type="text" class="form-control bg-body-secondary" />
                            <span asp-validation-for="@Model.Quiz.questions[i].correctAnswer" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="mt-2 border border-primary rounded">
                        @for (int j = 0; j < Model.Quiz.questions[i].answers?.Count; j++)
                        {

                            <div class="d-none">
                                <label asp-for="@Model.Quiz.questions[i].answers[j].id" class="col-form-label"></label>
                                <input asp-for="@Model.Quiz.questions[i].answers[j].id" type="text" class="form-control bg-body-secondary" />
                            </div>
                            <div class="d-none">
                                <label asp-for="@Model.Quiz.questions[i].answers[j].questionId" class="col-form-label"></label>
                                <input asp-for="@Model.Quiz.questions[i].answers[j].questionId" type="text" class="form-control bg-body-secondary" />
                            </div>

                            <label asp-for="@Model.Quiz.questions[i].answers[j].value" class="col-form-label mx-2"></label>
                            <div class="d-flex">
                                <div class="w-50 px-2">
                                    <input asp-for="@Model.Quiz.questions[i].answers[j].value" type="text" class="form-control bg-body-secondary" />
                                    <span asp-validation-for="@Model.Quiz.questions[i].answers[j].value" class="text-danger"></span>
                                </div>
                                <div class="col-auto align-self-start">
                                    <button asp-route-id="@(j)" asp-route-questId="@(i)" asp-action="DeleteAnswer" asp-controller="ManageQuiz" class="btn btn-danger w-100" type="submit"><i class="bi bi-x-lg"></i></button>
                                </div>
                            </div>
                        }
                        <div class="m-1 p-2">
                            <button asp-route-id="@(i)" asp-action="AddAnswer" asp-controller="ManageQuiz" class="btn btn-outline-primary" type="submit">Add answer</button>
                        </div>
                    </div>
                </div>
            </div>
            
            
        }
        <div>
            <button asp-route-id="@(Model.Quiz.questions?.Count)" asp-action="AddQuestion" asp-controller="ManageQuiz" class="btn btn-outline-primary" type="submit">Add question</button>
        </div>
    </div>

    <div class="w-100 bg-danger text-bg-light" style="text-align:center;">
        <p>
            @text
        </p>
    </div>
    
    <div class="d-flex mb-3">
        <button asp-action="SaveQuizChanges" asp-controller="ManageQuiz" class="btn btn-success w-50" type="submit">Save</button>
        <a asp-action="Index" asp-controller="Main" class="btn btn-warning w-50" type="button">Cancel</a>
    </div>
</form>



@section Scripts{
    @{
        
    }
}

Quiz-Application-MVC/Views/Quiz/QuizResults.cshtml
@model QuizResultData
@{


}

<div class="">
    <div class="" style="min-height:180px;">
    </div>
    <div class="row h1 text-center">
        <p>Quiz Result </p>
    </div>
    <div class="row">
        <div class="h3">Quiz name : @Model.Name</div>
        <div class="h3 mt-2">Progress:</div>
        <div class="progress my-2" style="height:25px;">
            <div class="progress-bar fw-bold text-dark @Model.progressColor" style="width:@(Model.progressValue == 0 ? 100 : Model.progressValue)%;" role="progressbar" aria-valuenow="@Model.TotalNumberOfCorrectAnswers" aria-valuemin="0" aria-valuemax="@Model.TotalNumberOfQuestions">@(Model.progressValue)%</div>
        </div>
    </div>
    <div>
        <div class="h3 mt-2">Finished at : @Model.FinishedAtTime</div>
    </div>
    <div class="d-flex justify-content-center mt-5">
        <a asp-action="Index" asp-controller="Main" class="btn btn-primary w-50" type="button">Done</a>
    </div>
</div>

Quiz-Application-MVC/Views/Quiz/StartQuiz.cshtml
@model QuizViewModel
@{

}
<form class="form" method="post" action="FinishQuiz">
    <div class="row mb-3">
        <h1>
            @Model.Quiz.name
        </h1>
    </div>
    <div class="row mx-4">
        <ol class="col">
            @foreach (var question in Model.QuestionPool)
            {
                <li class="h2">@Model.Quiz.questions.First(x => x.id == question.Key).value</li>

                <div class="list-group row">
                    @foreach (var answer in question.Value)
                    {
                        <input asp-for="@Model.QuestionPool[question.Key][answer.Key]" type="checkbox" class="btn-check" id="@(answer.Key)" autocomplete="off"/>
                        <label asp-for="@Model.QuestionPool[question.Key][answer.Key]" class="btn btn-outline-dark fw-bold list-group-item list-group-item-action" for="@(answer.Key)">@Model.Quiz.questions.First(x => x.id == question.Key).answers.First(x => x.id == answer.Key).value</label>

                        <br>
                    }
                </div>
            }
        </ol>
    </div>
    <div class="row">
        <button asp-route-id="@Model.Quiz.id" asp-action="FinishQuiz" asp-controller="Quiz" class="btn btn-primary w-50" type="submit">Finish</button>
        <a asp-action="Index" asp-controller="Main" class="btn btn-outline-dark w-50" type="button">Exit</a>
    </div>
</form>

Quiz-Application-MVC/Views/Shared/_ErrorLabel.cshtml
@model string

<div>
    <p>@Model</p>
</div>

@section Scripts{
    @{
    }
}

Quiz-Application-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-utilities.css" rel="stylesheet" />
</head>
<body class="bg-light d-flex min-vh-100">
    <header class="">
        <nav class="navbar navbar-expand-lg bg-primary border-bottom rounded-bottom border-primary" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" style="font-weight:bold;" asp-area="" asp-controller="Main" asp-action="Index">Quiz App</a>
                <div class="row navbar-nav">
                    <div class="nav-item col align-self-start">
                        <a class="nav-link active" asp-controller="Main" asp-action="Index">
                            Quizes
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </div>
                    <div class="nav-item col align-self-start">
                        <a class="nav-link active" asp-controller="Main" asp-action="Index">
                            Login
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-light-subtle border border-primary rounded my-3 flex-grow-1">
        <main role="main" class="pt-2">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer fixed-bottom bg-primary text-bg-primary d-flex align-items-center flex-grow-0" data-bs-theme="dark" style="position:relative; min-height:50px;">
        <div class="container">
            <div class="row-cols-auto">
                &copy; 2024 - Quiz App
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.esm.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.esm.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>